development:
  encoding: utf8
  adapter: mysql
  database: rubyamf_development
  username: root
  password: 123
  socket: /opt/local/var/run/mysql5/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  database: rubyamf_test
  pool: 5
  username: root
  password: 123
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  database: rubyamf_production
  pool: 5
  username: root
  password: 123
  socket: /opt/local/var/run/mysql5/mysqld.sock
